# baseURL = "https://linuxhub-group.gitlab.io"
relativeURLs = true
languageCode = "zh-cn"
title = "RenzAlt"
theme = "github-style"
# googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  searchURL = "https://github.com/KanadeAlt"
  author = "RenzAlt"
  description = "likes cute and kawaii things <3."
  github = "RenzAlt"
#   facebook = "kanariaAlt"
#   twitter = "kanariaAlt"
#   linkedin = "kanariaAlt"
#   instagram = "kanariaAlt"
#   tumblr = "kanariaAlt"
#   email = "kanariaAlt@gmail.com"
  url = "https://github.com/KanadeAlt"
  keywords = "blog"
  rss = false
  lastmod = true
  userStatusEmoji = "❤️"
  favicon = "images/github.png"
  location = "SEKAI"
  enableGitalk = false
  enableGiscus = true

[params.giscus]
    repo = ""
    repo_id = ""
    category = "Show and tell"
    category_id = "DIC_kwDOIItJPM4CR1Sn"
    lang = "en"

#   [params.gitalk]
#     clientID = "Your client ID" 
#     clientSecret = "Your client secret" 
#     repo = "repo"
#     owner = "kanariaAlt"
#     admin = "kanariaAlt"
#     id = "location.pathname"
#     labels = "gitalk"
#     perPage = 15
#     pagerDirection = "last"
#     createIssueManually = true
#     distractionFreeMode = false

#   [[params.links]]
#     title = "Link2"
#     href = "https://kanariaAlt.com"
#     icon = "https://kanariaAlt.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
