# baseURL = "https://linuxhub-group.gitlab.io"
relativeURLs = true
languageCode = "zh-cn"
title = "KanariaAlt"
theme = "github-style"
# googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  searchURL = "https://github.com/mizuenaAlt"
  author = "0xKANARIA"
  description = "In solitude, where we are least alone."
  github = "mizuenaAlt"
#   facebook = "kanariaAlt"
#   twitter = "kanariaAlt"
#   linkedin = "kanariaAlt"
#   instagram = "kanariaAlt"
#   tumblr = "kanariaAlt"
#   email = "kanariaAlt@gmail.com"
  url = "https://github.com/mizuenaAlt"
  keywords = "blog"
  rss = false
  lastmod = true
  userStatusEmoji = "❤️"
  favicon = "images/github.png"
  location = "SEKAI"
  enableGitalk = false

#   [params.gitalk]
#     clientID = "Your client ID" 
#     clientSecret = "Your client secret" 
#     repo = "repo"
#     owner = "kanariaAlt"
#     admin = "kanariaAlt"
#     id = "location.pathname"
#     labels = "gitalk"
#     perPage = 15
#     pagerDirection = "last"
#     createIssueManually = true
#     distractionFreeMode = false

#   [[params.links]]
#     title = "Link2"
#     href = "https://kanariaAlt.com"
#     icon = "https://kanariaAlt.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]